.data
.pushsection .hyp.reloc, "a"
.global __hyp_section_.hyp.idmap.text
.word 0
.reloc 0, R_AARCH64_PREL32, __hyp_section_.hyp.idmap.text + 0xc20
.word 0
.reloc 4, R_AARCH64_PREL32, __hyp_section_.hyp.idmap.text + 0xc28
.global __hyp_section_.hyp.text
.global __hyp_section_.hyp.rodata
.word 0
.reloc 8, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3e0
.word 0
.reloc 12, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x468
.word 0
.reloc 16, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x470
.word 0
.reloc 20, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x4a8
.word 0
.reloc 24, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x4c8
.word 0
.reloc 28, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x4e0
.word 0
.reloc 32, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x548
.word 0
.reloc 36, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x5c0
.word 0
.reloc 40, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x5e0
.word 0
.reloc 44, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x668
.word 0
.reloc 48, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x670
.word 0
.reloc 52, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x6a8
.word 0
.reloc 56, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x6c8
.word 0
.reloc 60, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x6e0
.word 0
.reloc 64, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x748
.word 0
.reloc 68, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x9c8
.word 0
.reloc 72, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x9d0
.word 0
.reloc 76, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x9d8
.word 0
.reloc 80, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x9e0
.word 0
.reloc 84, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x9e8
.word 0
.reloc 88, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x9f0
.word 0
.reloc 92, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x9f8
.word 0
.reloc 96, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xa00
.word 0
.reloc 100, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xa08
.word 0
.reloc 104, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xa10
.word 0
.reloc 108, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xa18
.word 0
.reloc 112, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xa20
.word 0
.reloc 116, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xa28
.word 0
.reloc 120, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xa30
.word 0
.reloc 124, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xa38
.word 0
.reloc 128, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xa40
.word 0
.reloc 132, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xa48
.word 0
.reloc 136, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xa50
.word 0
.reloc 140, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xa58
.word 0
.reloc 144, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xa60
.word 0
.reloc 148, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xa68
.word 0
.reloc 152, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xa70
.word 0
.reloc 156, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xa78
.word 0
.reloc 160, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xa80
.word 0
.reloc 164, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0xa88
.word 0
.reloc 168, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1da0
.word 0
.reloc 172, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1db8
.word 0
.reloc 176, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1df0
.word 0
.reloc 180, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1e08
.word 0
.reloc 184, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1e40
.word 0
.reloc 188, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1e58
.word 0
.reloc 192, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1e90
.word 0
.reloc 196, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1ea8
.word 0
.reloc 200, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1ee0
.word 0
.reloc 204, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1ef8
.word 0
.reloc 208, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1f30
.word 0
.reloc 212, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1f48
.word 0
.reloc 216, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1f80
.word 0
.reloc 220, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1f98
.word 0
.reloc 224, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1fd0
.word 0
.reloc 228, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x1fe8
.word 0
.reloc 232, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2020
.word 0
.reloc 236, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2038
.word 0
.reloc 240, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2070
.word 0
.reloc 244, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2088
.word 0
.reloc 248, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x20c0
.word 0
.reloc 252, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x20d8
.word 0
.reloc 256, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2110
.word 0
.reloc 260, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2128
.word 0
.reloc 264, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2160
.word 0
.reloc 268, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2178
.word 0
.reloc 272, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x21b0
.word 0
.reloc 276, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x21c8
.word 0
.reloc 280, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2200
.word 0
.reloc 284, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2218
.word 0
.reloc 288, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2250
.word 0
.reloc 292, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2268
.word 0
.reloc 296, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x22a0
.word 0
.reloc 300, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x22b8
.word 0
.reloc 304, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x22f0
.word 0
.reloc 308, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2308
.word 0
.reloc 312, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2340
.word 0
.reloc 316, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2358
.word 0
.reloc 320, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x23a8
.word 0
.reloc 324, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x23e0
.word 0
.reloc 328, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x23f8
.word 0
.reloc 332, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2430
.word 0
.reloc 336, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2448
.word 0
.reloc 340, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2480
.word 0
.reloc 344, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2498
.word 0
.reloc 348, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x24e8
.word 0
.reloc 352, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2520
.word 0
.reloc 356, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2538
.word 0
.reloc 360, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2570
.word 0
.reloc 364, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2588
.word 0
.reloc 368, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x25d8
.word 0
.reloc 372, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2628
.word 0
.reloc 376, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2660
.word 0
.reloc 380, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2678
.word 0
.reloc 384, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x26c8
.word 0
.reloc 388, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2718
.word 0
.reloc 392, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2768
.word 0
.reloc 396, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x27a0
.word 0
.reloc 400, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x27b8
.word 0
.reloc 404, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x27f0
.word 0
.reloc 408, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2808
.word 0
.reloc 412, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2858
.word 0
.reloc 416, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x28a8
.word 0
.reloc 420, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x28e0
.word 0
.reloc 424, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x28f8
.word 0
.reloc 428, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2930
.word 0
.reloc 432, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2948
.word 0
.reloc 436, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2998
.word 0
.reloc 440, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x29e8
.word 0
.reloc 444, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2a20
.word 0
.reloc 448, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2a38
.word 0
.reloc 452, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2a70
.word 0
.reloc 456, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2a88
.word 0
.reloc 460, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2ac0
.word 0
.reloc 464, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2ad8
.word 0
.reloc 468, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2b28
.word 0
.reloc 472, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2b78
.word 0
.reloc 476, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2bc8
.word 0
.reloc 480, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2c18
.word 0
.reloc 484, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2c68
.word 0
.reloc 488, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2ca0
.word 0
.reloc 492, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2cb8
.word 0
.reloc 496, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2cf0
.word 0
.reloc 500, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2d08
.word 0
.reloc 504, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2d40
.word 0
.reloc 508, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2d58
.word 0
.reloc 512, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2da8
.word 0
.reloc 516, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2df8
.word 0
.reloc 520, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2e48
.word 0
.reloc 524, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2e98
.word 0
.reloc 528, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2ee8
.word 0
.reloc 532, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2f20
.word 0
.reloc 536, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2f38
.word 0
.reloc 540, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2f70
.word 0
.reloc 544, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2f88
.word 0
.reloc 548, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2fc0
.word 0
.reloc 552, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x2fd8
.word 0
.reloc 556, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3010
.word 0
.reloc 560, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3028
.word 0
.reloc 564, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3060
.word 0
.reloc 568, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3078
.word 0
.reloc 572, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x30b0
.word 0
.reloc 576, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x30c8
.word 0
.reloc 580, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3100
.word 0
.reloc 584, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3118
.word 0
.reloc 588, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3150
.word 0
.reloc 592, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3168
.word 0
.reloc 596, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x31a0
.word 0
.reloc 600, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x31f0
.word 0
.reloc 604, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3240
.word 0
.reloc 608, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3290
.word 0
.reloc 612, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x32a8
.word 0
.reloc 616, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x32e0
.word 0
.reloc 620, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3330
.word 0
.reloc 624, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3380
.word 0
.reloc 628, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x33d0
.word 0
.reloc 632, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3420
.word 0
.reloc 636, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x3470
.word 0
.reloc 640, R_AARCH64_PREL32, __hyp_section_.hyp.rodata + 0x34c0
.popsection
